### PR TITLE
vip, vi and vi_model S3 methods for  workflow objects

### PR DESCRIPTION
**Pull request by Athospd**
vip, vi and vi_model S3 methods for  workflow objects

ref: https://tidymodels.github.io/workflows/

### CODE REVIEW

**Comment by bgreenwell** [comment]
Thanks for the PR @Athospd, any chance you can add some tests? 

Example here: https://github.com/koalaverse/vip/blob/master/inst/tinytest/test_pkg_parsnip.R

**Comment by Athospd** [comment]
Of course! I looked for the tests in the wrong folder =P (there is a empty 'tests' folder btw).

**Comment by topepo** [comment]
Can I suggest that adding a function to check to see if the workflow has been fit (right before passing the fit object in)? 

```r
check_wflow_fittted <- function(x) {
  if (is.null(x$fit$fit)) {
    stop("Please fit the workflow.")
  }
  invisible(x)
}
```

**Comment by bgreenwell** [comment]
Updated and addressed in https://github.com/koalaverse/vip/pull/128.

**Pull request closed without merging**
