### PR TITLE
importance scores for PLS models from the mixOmics package.

### PR DESCRIPTION
**Pull request by topepo**

### CODE REVIEW

**Comment by topepo** [comment]
CI errors are coming from mlr tests. Any ideas? Let me know if I need to change something.

**Comment by bgreenwell** [comment]
@topepo Not sure why that's happening, but I'll look into it. In the ubuntu-20.04 (release) env, I'm also seeing `Error: Package suggested but not available: ‘mixOmics’`. Any thoughts there?

**Comment by topepo** [comment]
I'm not sure why it isn't installed in that configuration. If works for our packages that use it. 

Can I update you r GutHub actions files in a different PR? That might be the difference?

**Comment by bgreenwell** [comment]
Also, I'm going to merge this into the devel branch so I can manually run the tests and see what's going on with **mlr**.

**Comment by topepo** [comment]
In case you haven't seen it, [`usethis::pr_fetch()`](https://usethis.r-lib.org/reference/pull-requests.html) is great for opening PR's locally.

**Comment by bgreenwell** [comment]
@topepo, sorry for the long delay; I have a new book coming out and that has literally eaten into all of my spare time. In any case, the issue is coming from the **mixOmics** tests; in there, you use `mixOmics::funs()` but still load the package, which overwrites **vip**'s `vip()` function with the one from **mixOmics**. I plan to merge this and push a new release to CRAN this weekend that fixes another bug that the CRAN maintainers pointed out. 

Also, after the holiday, I plan to take a hard look at incorporating **yardstick** for the performance metrics.

**Pull request merged**
